name: Build and Test

on:
  push:
    branches:
      - main
      - master
      - develop
      - feature*
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - master
      - develop
      - feature*
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build And Test Job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test
